
export enum MessageType {
    USER_TOKEN = "USER_TOKEN",
    CHAT_MESSAGE = "CHAT_MESSAGE",
    FRIEND_LIST = "FRIEND_LIST",
    FRIEND_REQUEST_LIST = "FRIEND_REQUEST_LIST",
    GAME = "GAME",
    INVITE_LIST = "INVITE_LIST"
}
