# db name: webgamesdb
# database service: MySql
# engine: InnoDB
# port: 3306
# userName: webgames
# password: webgamespw


CREATE TABLE WG_USER (
  ID BIGINT(10) AUTO_INCREMENT,
  USER_NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UQ_USER_NAME UNIQUE (USER_NAME)
) ENGINE = InnoDB;


CREATE TABLE WG_FRIEND (
  FRIEND_ID BIGINT(10) NOT NULL,
  FRIEND_TO_ID BIGINT(10) NOT NULL,
  PRIMARY KEY (FRIEND_ID, FRIEND_TO_ID)
) ENGINE=InnoDB;
ALTER TABLE WG_FRIEND
  ADD CONSTRAINT FRIEND_ID FOREIGN KEY (FRIEND_ID) REFERENCES WG_USER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT FRIEND_TO_ID FOREIGN KEY (FRIEND_TO_ID) REFERENCES WG_USER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


CREATE TABLE WG_FRIEND_REQUEST (
  REQUESTER_ID BIGINT(10) NOT NULL,
  REQUESTED_ID BIGINT(10) NOT NULL,
  PRIMARY KEY (REQUESTER_ID, REQUESTED_ID)
) ENGINE = InnoDB;
ALTER TABLE WG_FRIEND_REQUEST
  ADD CONSTRAINT FK_REQUESTED_ID FOREIGN KEY (REQUESTED_ID) REFERENCES WG_USER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT FK_REQUESTER_ID FOREIGN KEY (REQUESTER_ID) REFERENCES WG_USER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

